
const Inventory = [
  {
    id: "0",
    title: "Blank",
    price: 0,
    desc: "Endless Possibilities",
    amount: 2,
  },
  {
    id: "1",
    title: "Letter A",
    price: 1,
    desc: "The Letter A",
    amount: 9,
  },
  {
    id: "2",
    title: "Letter B",
    price: 3,
    desc: "The Letter B",
    amount: 2,
  },
  {
    id: "3",
    title: "Letter C",
    price: 3,
    desc: "The Letter C",
    amount: 2,
  },
  {
    id: "4",
    title: "Letter D",
    price: 2,
    desc: "The Letter D",
    amount: 4,
  },
  {
    id: "5",
    title: "Letter E",
    price: 1,
    desc: "The Letter E",
    amount: 12,
  },
  {
    id: "6",
    title: "Letter F",
    price: 4,
    desc: "The Letter F",
    amount: 2,
  },
  {
    id: "7",
    title: "Letter G",
    price: 2,
    desc: "The Letter G",
    amount: 3,
  },
  {
    id: "8",
    title: "Letter H",
    price: 4,
    desc: "The Letter H",
    amount: 2,
  },
  {
    id: "9",
    title: "Letter I",
    price: 1,
    desc: "The Letter I",
    amount: 9,
  },
  {
    id: "10",
    title: "Letter J",
    price: 8,
    desc: "The Letter J",
    amount: 1,
  },
  {
    id: "11",
    title: "Letter K",
    price: 5,
    desc: "The Letter K",
    amount: 9,
  },
  {
    id: "12",
    title: "Letter L",
    price: 1,
    desc: "The Letter L",
    amount: 4,
  },
  {
    id: "13",
    title: "Letter M",
    price: 3,
    desc: "The Letter M",
    amount: 2,
  },
  {
    id: "14",
    title: "Letter N",
    price: 6,
    desc: "The Letter N",
    amount: 1,
  },
  {
    id: "15",
    title: "Letter O",
    price: 1,
    desc: "The Letter O",
    amount: 8,
  },
  {
    id: "16",
    title: "Letter P",
    price: 3,
    desc: "The Letter P",
    amount: 2,
  },
  {
    id: "17",
    title: "Letter Q",
    price: 10,
    desc: "The Letter Q",
    amount: 1,
  },
  {
    id: "18",
    title: "Letter R",
    price: 6,
    desc: "The Letter R",
    amount: 1,
  },
  {
    id: "19",
    title: "Letter S",
    price: 1,
    desc: "The Letter S",
    amount: 4,
  },
  {
    id: "20",
    title: "Letter T",
    price: 1,
    desc: "The Letter T",
    amount: 6,
  },
  {
    id: "21",
    title: "Letter U",
    price: 1,
    desc: "The Letter U",
    amount: 4,
  },
  {
    id: "22",
    title: "Letter V",
    price: 4,
    desc: "The Letter V",
    amount: 2,
  },
  {
    id: "23",
    title: "Letter W",
    price: 4,
    desc: "The Letter W",
    amount: 2,
  },
  {
    id: "24",
    title: "Letter X",
    price: 8,
    desc: "The Letter X",
    amount: 1,
  },
  {
    id: "25",
    title: "Letter Y",
    price: 4,
    desc: "The Letter Y",
    amount: 2,
  },
  {
    id: "26",
    title: "Letter Z",
    price: 10,
    desc: "The Letter Z",
    amount: 1,
  },
]
export default Inventory