const Inventory = [
  {
    id: "1",
    letter: "A",
    price: 1,
    desc: "The Letter A",
    amount: 9,
    image: "letA",
  },
  {
    id: "2",
    letter: "B",
    price: 3,
    desc: "The Letter B",
    amount: 2,
    image: "letB",
  },
  {
    id: "3",
    letter: "C",
    price: 3,
    desc: "The Letter C",
    amount: 2,
    image: "letC",
  },
  {
    id: "4",
    letter: "D",
    price: 2,
    desc: "The Letter D",
    amount: 4,
    image: "letD",
  },
  {
    id: "5",
    letter: "E",
    price: 1,
    desc: "The Letter E",
    amount: 12,
    image: "letE",
  },
  {
    id: "6",
    letter: "F",
    price: 4,
    desc: "The Letter F",
    amount: 2,
    image: "letF",
  },
  {
    id: "7",
    letter: "G",
    price: 2,
    desc: "The Letter G",
    amount: 3,
    image: "letG",
  },
  {
    id: "8",
    letter: "H",
    price: 4,
    desc: "The Letter H",
    amount: 2,
    image: "letH",
  },
  {
    id: "9",
    letter: "I",
    price: 1,
    desc: "The Letter I",
    amount: 9,
    image: "letI",
  },
  {
    id: "10",
    letter: "J",
    price: 8,
    desc: "The Letter J",
    amount: 1,
    image: "letJ",
  },
  {
    id: "11",
    letter: "K",
    price: 5,
    desc: "The Letter K",
    amount: 9,
    image: "letK",
  },
  {
    id: "12",
    letter: "L",
    price: 1,
    desc: "The Letter L",
    amount: 4,
    image: "letL",
  },
  {
    id: "13",
    letter: "M",
    price: 3,
    desc: "The Letter M",
    amount: 2,
    image: "letM",
  },
  {
    id: "14",
    letter: "N",
    price: 6,
    desc: "The Letter N",
    amount: 1,
    image: "letN",
  },
  {
    id: "15",
    letter: "O",
    price: 1,
    desc: "The Letter O",
    amount: 8,
    image: "letO",
  },
  {
    id: "16",
    letter: "P",
    price: 3,
    desc: "The Letter P",
    amount: 2,
    image: "letP",
  },
  {
    id: "17",
    letter: "Q",
    price: 10,
    desc: "The Letter Q",
    amount: 1,
    image: "letQ",
  },
  {
    id: "18",
    letter: "R",
    price: 6,
    desc: "The Letter R",
    amount: 1,
    image: "letR",
  },
  {
    id: "19",
    letter: "S",
    price: 1,
    desc: "The Letter S",
    amount: 4,
    image: "letS",
  },
  {
    id: "20",
    letter: "T",
    price: 1,
    desc: "The Letter T",
    amount: 6,
    image: "letT",
  },
  {
    id: "21",
    letter: "U",
    price: 1,
    desc: "The Letter U",
    amount: 4,
    image: "letU",
  },
  {
    id: "22",
    letter: "V",
    price: 4,
    desc: "The Letter V",
    amount: 2,
    image: "letV",
  },
  {
    id: "23",
    letter: "W",
    price: 4,
    desc: "The Letter W",
    amount: 2,
    image: "letW",
  },
  {
    id: "24",
    letter: "X",
    price: 8,
    desc: "The Letter X",
    amount: 1,
    image: "letX",
  },
  {
    id: "25",
    letter: "Y",
    price: 4,
    desc: "The Letter Y",
    amount: 2,
    image: "letY",
  },
  {
    id: "26",
    letter: "Z",
    price: 10,
    desc: "The Letter Z",
    amount: 1,
    image: "letZ",
  },
  {
    id: "0",
    letter: "Blank",
    price: 0,
    desc: "Endless Possibilities",
    amount: 2,
    image: "letBlank",
  },
];
export default Inventory;
